"""System class mappings used by :class:`Building`.

The mapping keys remain plain string values because DataSourceCSV and
DataSourceDjango still provide string system identifiers. Enums are used here
only as a central source for those string values.
"""

from dibs_computing_core.iso_simulator.emission_system import (
    AirConditioning,
    NoCooling,
    NoHeating,
    SurfaceHeatingCooling,
    ThermallyActivated,
)
from dibs_computing_core.iso_simulator.supply_system import (
    AbsorptionRefrigerationSystem,
    AirCooledPistonScroll,
    AirCooledPistonScrollMulti,
    BiogasBoilerCondensingBefore95,
    BiogasBoilerCondensingFrom95,
    BiogasOilBoilerCondensingFrom95,
    BiogasOilBoilerCondensingImproved,
    BiogasOilBoilerLowTempBefore95,
    CoalSolidFuelBoiler,
    DirectCooler,
    DirectHeater,
    DistrictCooling,
    DistrictHeating,
    ElectricHeating,
    GasBoilerCondensingBefore95,
    GasBoilerCondensingFrom95,
    GasBoilerCondensingImproved,
    GasBoilerLowTempBefore87,
    GasBoilerLowTempBefore95,
    GasBoilerLowTempFrom95,
    GasBoilerLowTempSpecialFrom78,
    GasBoilerLowTempSpecialFrom95,
    GasBoilerStandardBefore86,
    GasBoilerStandardBefore95,
    GasBoilerStandardFrom95,
    GasCHP,
    GasEnginePistonScroll,
    HeatPumpAirSource,
    HeatPumpGroundSource,
    LGasBoilerCondensingBefore95,
    LGasBoilerCondensingFrom95,
    LGasBoilerCondensingImproved,
    LGasBoilerLowTempBefore87,
    LGasBoilerLowTempBefore95,
    LGasBoilerLowTempFrom95,
    NoCooler,
    NoHeater,
    OilBoilerCondensingBefore95,
    OilBoilerCondensingFrom95,
    OilBoilerCondensingImproved,
    OilBoilerLowTempBefore87,
    OilBoilerLowTempBefore95,
    OilBoilerLowTempFrom95,
    OilBoilerStandardBefore86,
    OilBoilerStandardFrom95,
    SolidFuelLiquidFuelFurnace,
    WaterCooledPistonScroll,
    WoodChipSolidFuelBoiler,
    WoodPelletSolidFuelBoiler,
    WoodSolidFuelBoilerCentral,
)
from dibs_computing_core.iso_simulator.building_simulator.system_enums import (
    CoolingSystem,
    EmissionSystem,
    HeatingSystem,
)


BUILDING_EMISSION_SYSTEM_MAPPING = {
    EmissionSystem.AIR_CONDITIONING.value: AirConditioning,
    EmissionSystem.SURFACE_HEATING_COOLING.value: SurfaceHeatingCooling,
    EmissionSystem.THERMALLY_ACTIVATED.value: ThermallyActivated,
    EmissionSystem.NO_COOLING.value: NoCooling,
    EmissionSystem.NO_HEATING.value: NoHeating,
}

HEATING_SUPPLY_SYSTEM_MAPPING = {
    HeatingSystem.OIL_BOILER_STANDARD_BEFORE_86.value: OilBoilerStandardBefore86,
    HeatingSystem.OIL_BOILER_STANDARD_FROM_95.value: OilBoilerStandardFrom95,
    HeatingSystem.OIL_BOILER_LOW_TEMP_BEFORE_87.value: OilBoilerLowTempBefore87,
    HeatingSystem.OIL_BOILER_LOW_TEMP_BEFORE_95.value: OilBoilerLowTempBefore95,
    HeatingSystem.OIL_BOILER_LOW_TEMP_FROM_95.value: OilBoilerLowTempFrom95,
    HeatingSystem.OIL_BOILER_CONDENSING_BEFORE_95.value: OilBoilerCondensingBefore95,
    HeatingSystem.OIL_BOILER_CONDENSING_FROM_95.value: OilBoilerCondensingFrom95,
    HeatingSystem.OIL_BOILER_CONDENSING_IMPROVED.value: OilBoilerCondensingImproved,
    HeatingSystem.GAS_BOILER_STANDARD_BEFORE_86.value: GasBoilerStandardBefore86,
    HeatingSystem.GAS_BOILER_STANDARD_BEFORE_95.value: GasBoilerStandardBefore95,
    HeatingSystem.GAS_BOILER_STANDARD_FROM_95.value: GasBoilerStandardFrom95,
    HeatingSystem.GAS_BOILER_LOW_TEMP_BEFORE_87.value: GasBoilerLowTempBefore87,
    HeatingSystem.LGAS_BOILER_LOW_TEMP_BEFORE_87.value: LGasBoilerLowTempBefore87,
    HeatingSystem.GAS_BOILER_LOW_TEMP_BEFORE_95.value: GasBoilerLowTempBefore95,
    HeatingSystem.LGAS_BOILER_LOW_TEMP_BEFORE_95.value: LGasBoilerLowTempBefore95,
    HeatingSystem.GAS_BOILER_LOW_TEMP_FROM_95.value: GasBoilerLowTempFrom95,
    HeatingSystem.LGAS_BOILER_LOW_TEMP_FROM_95.value: LGasBoilerLowTempFrom95,
    HeatingSystem.BIOGAS_OIL_BOILER_LOW_TEMP_BEFORE_95.value: BiogasOilBoilerLowTempBefore95,
    HeatingSystem.GAS_BOILER_LOW_TEMP_SPECIAL_FROM_78.value: GasBoilerLowTempSpecialFrom78,
    HeatingSystem.GAS_BOILER_LOW_TEMP_SPECIAL_FROM_95.value: GasBoilerLowTempSpecialFrom95,
    HeatingSystem.GAS_BOILER_CONDENSING_BEFORE_95.value: GasBoilerCondensingBefore95,
    HeatingSystem.LGAS_BOILER_CONDENSING_BEFORE_95.value: LGasBoilerCondensingBefore95,
    HeatingSystem.BIOGAS_BOILER_CONDENSING_BEFORE_95.value: BiogasBoilerCondensingBefore95,
    HeatingSystem.BIOGAS_BOILER_CONDENSING_FROM_95.value: BiogasBoilerCondensingFrom95,
    HeatingSystem.GAS_BOILER_CONDENSING_FROM_95.value: GasBoilerCondensingFrom95,
    HeatingSystem.LGAS_BOILER_CONDENSING_FROM_95.value: LGasBoilerCondensingFrom95,
    HeatingSystem.BIOGAS_OIL_BOILER_CONDENSING_FROM_95.value: BiogasOilBoilerCondensingFrom95,
    HeatingSystem.GAS_BOILER_CONDENSING_IMPROVED.value: GasBoilerCondensingImproved,
    HeatingSystem.LGAS_BOILER_CONDENSING_IMPROVED.value: LGasBoilerCondensingImproved,
    HeatingSystem.BIOGAS_OIL_BOILER_CONDENSING_IMPROVED.value: BiogasOilBoilerCondensingImproved,
    HeatingSystem.WOOD_CHIP_SOLID_FUEL_BOILER.value: WoodChipSolidFuelBoiler,
    HeatingSystem.WOOD_PELLET_SOLID_FUEL_BOILER.value: WoodPelletSolidFuelBoiler,
    HeatingSystem.WOOD_SOLID_FUEL_BOILER_CENTRAL.value: WoodSolidFuelBoilerCentral,
    HeatingSystem.COAL_SOLID_FUEL_BOILER.value: CoalSolidFuelBoiler,
    HeatingSystem.SOLID_FUEL_LIQUID_FUEL_FURNACE.value: SolidFuelLiquidFuelFurnace,
    HeatingSystem.HEAT_PUMP_AIR_SOURCE.value: HeatPumpAirSource,
    HeatingSystem.HEAT_PUMP_GROUND_SOURCE.value: HeatPumpGroundSource,
    HeatingSystem.GAS_CHP.value: GasCHP,
    HeatingSystem.DISTRICT_HEATING.value: DistrictHeating,
    HeatingSystem.ELECTRIC_HEATING.value: ElectricHeating,
    HeatingSystem.DIRECT_HEATER.value: DirectHeater,
    HeatingSystem.NO_HEATING.value: NoHeater,
}

COOLING_SUPPLY_SYSTEM_MAPPING = {
    CoolingSystem.AIR_COOLED_PISTON_SCROLL.value: AirCooledPistonScroll,
    CoolingSystem.AIR_COOLED_PISTON_SCROLL_MULTI.value: AirCooledPistonScrollMulti,
    CoolingSystem.WATER_COOLED_PISTON_SCROLL.value: WaterCooledPistonScroll,
    CoolingSystem.ABSORPTION_REFRIGERATION_SYSTEM.value: AbsorptionRefrigerationSystem,
    CoolingSystem.DISTRICT_COOLING.value: DistrictCooling,
    CoolingSystem.GAS_ENGINE_PISTON_SCROLL.value: GasEnginePistonScroll,
    CoolingSystem.DIRECT_COOLER.value: DirectCooler,
    CoolingSystem.NO_COOLING.value: NoCooler,
}

BUILDING_SUPPLY_SYSTEM_MAPPING = {
    **HEATING_SUPPLY_SYSTEM_MAPPING,
    **COOLING_SUPPLY_SYSTEM_MAPPING,
}